### ISSUE TITLE
Database for Network

### ISSUE THREAD

**Issue by caseyli92** [GeospatialResearch/Digital-Twins#113]

**Comment by LukeParky** [comment]
Hi @caseyli92, is this something that you have made progress towards? And do you think its a priority for Phase 1? I am not sure on the need for it

**Comment by caseyli92** [comment]
@LukeParky, this was mentioned as a possible need earlier, but it's not necessary at the moment. It relates to the river module for the flood resilience project. The river network metadata are currently stored in the PostGIS database, and the module is functioning as intended. Additionally, I believe our focus has now shifted to the otakaro project, where the current funding is allocated, rather than flood-related purposes.

**Comment by LukeParky** [comment]
That's what I expected. Closing it as not planned, and we can revive it if needed in the future.
