### ISSUE TITLE
Learning task: Find which bridges cross which rivers

### ISSUE THREAD

**Issue by LukeParky** [GeospatialResearch/Digital-Twins#156]
This is an issue to onboard somone with basics of interacting with the Digital Twin codebase.

Your task is to add a new database table called `bridges_over_rivers`.
This will contain all the bridges in your area of interest that are over a river.
It will have columns `bridge_id` and column `river_name`.

Before you start this task, assign yourself to this issue and make sure it has status "In Progress".
Then create a new git branch called `learning_YOUR_NAME`.
Assosciate this issue with your new branch.

Make commits and push them as you go.

1. The first step is to load the data you need into the database. You need the [NZ River Name Polygons](https://data.linz.govt.nz/layer/103631-nz-river-name-polygons-pilot/) and [NZ Bridge centrelines](https://data.linz.govt.nz/layer/50244-nz-bridge-centrelines-topo-150k/) datasets. Add these datasets to `src/digitaltwin/static_boundary_conditions.json` and they will be automatically downloaded into a database table for any areas of interest selected later.

2. Add a new file `src/digitaltwin/bridges/bridges_over_rivers.py`, with a `main` function that is called by `run_all.py`

3. In this new bridges file, read the data from the new database tables into two `geopandas.GeoDataFrame`s and spatially join them by intersect to create another `GeoDataFrame` caled `bridge_river_join`.
4. Rename and remove columns from `bridge_river_join` until you're left with `bridge_id` and `river_name` and the bridge geometry column.
5. Save this to the database using `GeoDataFrame.to_postgis`.

Once you have completed this, create a Pull Request and assign someone to look at it. It helps to send them a message as well.

Code that may be useful for referencing during this task includes:
- Retrieving data from database: `retrieve_building_outlines` from  [flooded_buildings.py](https://github.com/GeospatialResearch/Digital-Twins/blob/3ddbe9f71a739b4e482f7f82c264a1da9f879948/src/flood_model/flooded_buildings.py)
- Spatial Joins: `categorise_buiding_as_flooded` from [flooded_buildings.py](https://github.com/GeospatialResearch/Digital-Twins/blob/3ddbe9f71a739b4e482f7f82c264a1da9f879948/src/flood_model/flooded_buildings.py)

If you have questions ask them.

**Comment by Martin20494** [comment]
The task is to help @Martin20494 to understand how digital github works and it was achieved.
