### ISSUE TITLE
Add additional more strict python linting rules for documentation

### ISSUE THREAD

**Issue by LukeParky** [GeospatialResearch/Digital-Twins#159]
Add additional auto linting rules to the github runner.
Additional rules required include but are not limited to:

- [x] All function/method parameters must have type annotations in-code.
- [x] All functions/methods must have return type hinting (`None` doesn't need to be explicit if it's easy to exclude).
- [x] All functions/methods/classes/files must have a docstring.
- [x] All function/method parameters and returns must have descriptions in the docstrings.
- [x] All function/method parameters and returns must have type annotation in the docstrings.

It is not recommended to change the format we are already using to write out docstrings, since this works for sphinx autodoc and would be a large task.

**Comment by LukeParky** [comment]
@caseyli92 I was wondering if you would like to do this task to get some practice with github actions

**Comment by LukeParky** [comment]
We currently use flake8 for this, but if it doesn't have the rules available for linting documentation you may have to use pylint

**Comment by caseyli92** [comment]
Linked to PR #196, merged into `otakaro_digital_twin` branch.
