### ISSUE TITLE
Empty env variables with defaults do not  use default

### ISSUE THREAD

**Issue by LukeParky** [GeospatialResearch/Digital-Twins#168]
To reproduce:

1. Create an empty environment variable in the `.env`, for example `TEST_VARIABLE=`
2. Run the following code: 
    ```python
    from src.config import get_env_variable
    print(get_env_variable("TEST_VARIABLE", allow_empty=True, default="DEFAULT TEST VALUE"))
    ```

Expected result:
```python
"DEFAULT TEST VALUE"
```

Actual result:
```python
""
```

**Comment by LukeParky** [comment]
I have added failing tests in `test_config.py` for this issue to the associated branch https://github.com/GeospatialResearch/Digital-Twins/tree/168-empty-env-variables-with-defaults-do-not-use-default

**Comment by LukeParky** [comment]
My reccomendations are to replace the failing `get_env_variable` implementation with the implementation found here: https://github.com/LukeParky/NewZeaLiDAR/blob/6a83fad648d0700ae18a75afb056e2d8b5509cad/newzealidar/env_var.py

This would require changing all uses of `cast_to` parameter to regular casting, or revamping the handling to the nicer implementation found in https://github.com/GeospatialResearch/CO2-SA1-Viz/blob/Mode_Share/initialise_db/config.py

**Comment by anirudh1117** [comment]
Hi @LukeParky , Can i work on this ? , I have understand the code  of config.py "get_env_variable" and also the implementation you have mentioned. So you want to create all the functions to "get_env_variable" of different return types (cast) like "get_bool_env_variable" ? 

Thanks ,

**Comment by LukeParky** [comment]
Hi, @anirudh1117, thank you for reaching out and offering to work on this, but no pressure, since we have a development team actively working. However, if you would like to create a fork and submit a pull request for this issue, I would gladly review it.

And to answer your questions about the issue:
We would not require any more functions other than `get_env_variable` and `get_bool_env_variable`.
For example, if the use of the code required `get_env_variable("INT_VARIABLE", cast_to=int)` it would become `int(get_env_variable("INT_VARIABLE")`.

However, `bool` types need some extra checking since people might put in `"false"` and that needs to evaluate as `False`, hence why we will have a new `get_bool_env_variable`.

There is a branch `168-empty-env-variables-with-defaults-do-not-use-default` with tests that must pass (they can be modified slightly to match implementation)

**Comment by anirudh1117** [comment]
Hi @LukeParky , I have created a pull request for these changes. This is my first time when i have created a pull request to open source codebase , so please let me know if i have done anything wrong.

Thanks

**Comment by LukeParky** [comment]
Hi @anirudh1117, I have made some suggestions on your PR https://github.com/GeospatialResearch/Digital-Twins/pull/187
Please look through them and we can get this issue fixed.

Also, could you please request me as a reviewer on your PR, it seems I'm not able to request myself.

**Comment by LukeParky** [comment]
I have added an additional test case to my branch because I noted a bug.

If it is easy to fix in this piece of work please do, otherwise let me know and I will create a new issue for it.

```python
    def test_non_existent_env_var_allow_empty(self):
        self.assertEqual(config.get_env_variable("NON_INITIALISED_ENVIRONMENT_VARIABLE_TEST_KEY", allow_empty=True),
                         None)
```

**Comment by anirudh1117** [comment]
I have one simple doubt that how to run test cases , i tried running test_config.py but i got error "src module not found" , did i need to add src in PythonPATH or modify sys.path in test_config.py or is there any script i am missing 
(i have started server using docker)
Thanks

**Comment by anirudh1117** [comment]
`anirudh@Ultra-Ubuntu-VM:~/Anirudh_Code/opensource/digital-twins/Digital-Twins$ python3 -m unittest discover -s tests/test_config/
............
----------------------------------------------------------------------
Ran 12 tests in 0.007s

OK
`

Added case you mentioned  "test_non_existent_env_var_allow_empty"  and run above command it's giving 'ok' seems current implementation supports this case.
