### ISSUE TITLE
Refactor code into a traditional application structure

### ISSUE THREAD

**Issue by rosepearson** [GeospatialResearch/Digital-Twins#17]
@rosepearson and @Pooja3894 can do this together as a peer-programming exercise.

This gives a sense of the approaches that are avaliable @Pooja3894  and may make for interesting reading for yourself

https://realpython.com/python-application-layouts/

@LukeParky - let me know if there is a particular pattern you think is best suited to this project.

**Comment by LukeParky** [comment]
Closed by PR #102  with further work done by #120
