### ISSUE TITLE
Automatically close linked issues when the pull request is merged

### ISSUE THREAD

**Issue by caseyli92** [GeospatialResearch/Digital-Twins#205]
This functionality works when merging into the master branch but not when merging into the otakaro branch.

**Comment by LukeParky** [comment]
It looks like the best way to do this is going to be by replacing the default branch. I am investigating any issues that might cause.

**Comment by LukeParky** [comment]
I have updated the default branch and not expecting any issues. 

I've linked this issue to unrelated PR #210. The reason for this is that if merging the PR successfully closes this issue then we know it is resolved.
