### ISSUE TITLE
Refactor API definition plan to allow for easy future expansion

### ISSUE THREAD

**Issue by Flame1190** [GeospatialResearch/Digital-Twins#214]
Currently the API definition plan in `src/static/api_documentation.yml` requires some refactoring. Various schema and properties are written in a way that would require lots of duplicate code/re-implementation if it was to be expanded for future modules (such as the pollution model). This should be done in such a way that the API itself is not changed, so that we do not need to edit the front-end or back-ends to match. For example, `src/app.py` should not change.

- [ ] Refactor `src/static/api_documentation.yml`

**Comment by LukeParky** [comment]
I like this issue, I see the problems. I think it can be handled concurently as we add more modules to the API, rather than one large task now. I'm closing this so we don't allocate dev time on it when we don't have large amounts of changes to come to the API spec
