### ISSUE TITLE
Geofabrics is not installed alongside other packages

### ISSUE THREAD

**Issue by LukeParky** [GeospatialResearch/Digital-Twins#27]
1. Create a fresh conda environment
2. Install packages by following instructions in the readme etc.
3. Check if `geofabrics` is installed
```python
$ python
>>> import geofabrics
>>> import geofabrics.processor
```
No errors should be shown.

The documentation of the geofabrics repo may need to be update too to show installation using pypi or conda

**Comment by rosepearson** [comment]
closed as addressed in 38
