### ISSUE TITLE
fish_barrier_photo_url link goes to a locked sign-in

### ISSUE THREAD

**Issue by LukeParky** [GeospatialResearch/Digital-Twins#311]
CREASSiteFishBarrier dataset.
In the Feature Information, it links out to a 
fish_barrier_photo_url link which goes to a locked sign-in landing page for Fulcrum– suggest removing this link if unable to access photos.

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Add a new function 'get_building_data' to retrieve building information, including the CREASSiteFishBarrier dataset, while removing the inaccessible fish_barrier_photo_url link.

You can review changes in this commit: https://github.com/lkilu6456546/GeospatialResearch-Digital-Twins-311/commit/932598c4566ba4b6dddf08bca2bad470d952979f.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by caseyli92** [comment]
Decided not to exclude this dataset as it seem useful.
