### ISSUE TITLE
Documentation - wiki pages & tidy readme

### ISSUE THREAD

**Issue by rosepearson** [GeospatialResearch/Digital-Twins#32]
Focus on making the documentation less confusing.

Also split out some details into separate wiki pages. 

Look to Luke's visualisation framework, or Rose's GeoFabrics for possible examples - or other Python Libraries

**Comment by LukeParky** [comment]
Blocked by: #17 since the documentation will change significantly when this is landed

**Comment by LukeParky** [comment]
Related: #82.

**Comment by LukeParky** [comment]
It will be important to add documentation for:

- Instruction file specifications
- Processes
- Local development (e.g. running code in IDE)
- Changing parameters
- And more, please add to this comment

**Comment by LukeParky** [comment]
Some work done in #136 to tidy readme but more to do to make it a well-documented wiki
