### ISSUE TITLE
Change so that size of size_ids is being checked, not its value

### ISSUE THREAD

**Issue by LukeParky** [GeospatialResearch/Digital-Twins#35]
```suggestion
        if site_ids.size != 0:
```

_Originally posted by @LukeParky in https://github.com/GeospatialResearch/Digital-Twins/pull/19#discussion_r794068288_

**Comment by caseyli92** [comment]
Hi @LukeParky and @rosepearson, I also realised this while reviewing this python script, and I believe I have already made these changes (already landed in the 'master' branch). Slightly different to what Luke has suggested. See the screenshot below:

![image](https://user-images.githubusercontent.com/91578421/182465408-0384eeea-1fd7-4364-975a-72796487982b.png)

**Comment by LukeParky** [comment]
Hi @caseyli92, the top example checks if `site_ids` is empty, but the bottom one is not correct since `site_ids` is a numpy array and the truth value is ambiguous.

`if site_ids:` will throw an error so change it to `if site_ids.size:` or alternatively `if site_ids.size > 0:`

**Comment by caseyli92** [comment]
> Hi @caseyli92, good to see that you spotted it too, but we should make the change consistent because one of them will cause an error. The top example checks if `site_ids` is empty, but the bottom one is not correct since `site_ids` is a numpy array and the truth value of an array is ambiguous.
> 
> `if site_ids:` will throw an error so change it to `if site_ids.size:` or alternatively `if site_ids.size > 0:`

Hi @LukeParky , I believe the top one is a numpy array, but the bottom one is a list.

**Comment by LukeParky** [comment]
> > Hi @caseyli92, good to see that you spotted it too, but we should make the change consistent because one of them will cause an error. The top example checks if `site_ids` is empty, but the bottom one is not correct since `site_ids` is a numpy array and the truth value of an array is ambiguous.
> > `if site_ids:` will throw an error so change it to `if site_ids.size:` or alternatively `if site_ids.size > 0:`
> 
> Hi @LukeParky , I believe the top one is a numpy array, but the bottom one is a list.

Ah I see @caseyli92. I assumed they would be the same. It seems like a code smell to me, because they're named the same I thought they would be the same type. Also noticed there's a big chunk of duplicated code there. I think we can look at this later, after the rearchitecture #17. The reason why not to do it now is that this function may or may not be rewritten as part of the rearchitecture.

Blocked by: #17

**Comment by caseyli92** [comment]
This will be fixed in #53.
