### ISSUE TITLE
Add GitHub Action to automatically assign new issues to the Digital Twin Board project

### ISSUE THREAD

**Issue by LukeParky** [GeospatialResearch/Digital-Twins#43]
Another interesting action would be to automatically add new issues to the GH project.
https://github.com/marketplace/actions/assign-to-one-project is a possible marketplace action that could achieve this.

Would be a good issue to learn GitHub Actions @caseyli92.

**Comment by xandercai** [comment]
Test pass.

[Compile error when set up the Python environment using environment.yml](https://github.com/GeospatialResearch/Digital-Twins/actions/runs/3528396520)
Add issue to project #2: Issue https://github.com/GeospatialResearch/Digital-Twins/issues/73 opened by [xandercai](https://github.com/xandercai)
