### ISSUE TITLE
Remove redundant csv saving when saving HIRDs data to database

### ISSUE THREAD

**Issue by LukeParky** [GeospatialResearch/Digital-Twins#57]
Currently data is fetched from web, saved to CSV, read from CSV, saved to database.
Ideally, unless the CSV is required, we should not be saving it to CSV. Casey has found a way that we can read the web data into in-memory csv tools, perhaps this is the way?

**Comment by caseyli92** [comment]
I have checked with Matt, we can remove the redundant CSV saving.
